title: "Jared's Restaurants"
description: "Places I've been and liked"
baseurl: ""
url: "https://jrddupont.github.io"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - project.md
  - CLAUDE.md
  - README.md
  - vendor/
